# Prepare and setup insight

Read data generated by Zenodo repository titled "AIHW-People-with-disability-in-Australia-2018"[1] to prepare and setup data insight. The "AIHW-People-with-disability-in-Australia-2018" transforms data from the Australian Institute of Health and Welfare (AIHW). The AIHW data [2] contains data tables related to people with a disability and their engagement in labour force in Australia.

## Download data

1. Go to (https://doi.org/10.5281/zenodo.4939863) and download the repository. 
2. Unzip the repository on your working directory

## Import libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Read data

In [2]:
input_path = '../../DATA/AIHW-People-with-disability-in-Australia-2018/generated_data/'
input_file = 'transformed_data.csv'

In [3]:
df = pd.read_csv(input_path + input_file, sep=',', encoding='utf-8')
df

employment status  estimated number of people ('000)  \
0      In the labour force(d)                             1098.6   
1                 Employed(e)                              984.2   
2  Employed working full-time                              581.8   
3  Employed working part-time                              402.8   
4                  Unemployed                              112.7   
5  Not in the labour force(f)                              958.5   
6                       Total                             2057.5   

   proportion(%)  
0           53.4  
1           47.8  
2           28.3  
3           19.6  
4            5.5  
5           46.6  
6          100.0

The transformed data contains estimated number of people with a disability by employment status as well as the proportion. 

## Visualize data

Here, we'd like to visualize the generated data. Below code demonstrates how to visualize the data by using Matplot library.

**Matplot** : Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python.

In [7]:
from treelib import Node, Tree

tree = Tree()

tree.create_node("2,057,500 people aged 15-64 with disability", "root")  # No parent means its the root node
tree.create_node("In the labour force (53.4%)",  "In the labour force"   , parent="root")
tree.create_node("Not in the labour force (46.6%)",  "Not in the labour force"   , parent="root")
tree.create_node("Employed (47.8%)",  "employed"   , parent="In the labour force")
tree.create_node("Unemployed (5.5%)",  "unemployed"   , parent="In the labour force")
tree.create_node("Working full-time (28.3%)",  "full-time"   , parent="employed")
tree.create_node("Working part-time (19.6%)",  "part-time"   , parent="employed")
tree.save2file('img/disability participant to labour force.txt')
tree.show()

2,057,500 people aged 15-64 with disability
├── In the labour force (53.4%)
│   ├── Employed (47.8%)
│   │   ├── Working full-time (28.3%)
│   │   └── Working part-time (19.6%)
│   └── Unemployed (5.5%)
└── Not in the labour force (46.6%)



The above tree graph shows hierarchy structure within employment status of people aged 15-64 with disability. In the total 2,057,500 people aged 15-64 with disability people, 53.4% are belong to labour force while the other 46.6% are not in the labour force. In the 53.4% labour force, 47.8% are employed where 28.3% are full-time and 19.6% are part-time.

## Insight

**53.4% of working-age (aged 15-64) people with disability participated in the Australian labour force in 2018.**

In [5]:
value = float(df['proportion(%)'].iloc[0])
print('{}% of working-age (aged 15-64) people with disability participated in the Australian labour force in 2018.'.format(round(value, 1)))

53.4% of working-age (aged 15-64) people with disability participated in the Australian labour force in 2018.


## Conclusion

We extract insight "53.4% of working-age (aged 15-64) people with disability participated in the Australian labour force in 2018." from the transformed data. The transformed data generated by [1] that it contains information about population of disability and their engagement in labour force in Australia in 2018. According to the data, around 53.4% of working-age (aged 15-64) people with a disability participated in the Australian labour force in 2018.

The original data source of the transformed data are available at ABS [2].

## References

[1] Jihoon Woo, & Amir Aryani. (2021, June 13). AIHW-People-with-disability-in-Australia-2018 (Version 1.0.1). Zenodo. http://doi.org/10.5281/zenodo.4939863

[2] AIHW. People with disability in Australia, Data tables: Employment supplementary data tables, 2020, Australian Institute of Health and Welfare, [Dataset] Available: https://www.aihw.gov.au/reports/disability/people-with-disability-in-australia/data. [Accessed: January 4, 2021].